name: Observability Stack

on:
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load inventory
        shell: bash
        run: |
          set -a
          source inventory/hosts.env
          set +a
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV

      - name: Copy manifests to bastion home
        shell: bash
        run: |
          rsync -av manifests/ /home/kubeadmin/manifests/

      - name: Deploy Observability from bastion shell
        shell: bash
        run: |
          ssh kubeadmin@localhost <<'EOF'
          set -euxo pipefail
          export KUBECONFIG=/home/kubeadmin/kubeconfig.yaml

          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f /home/kubeadmin/manifests/monitoring
          EOF
