name: Observability Stack

on:
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Prometheus Stack
        run: |
          ssh kubeadmin@192.168.29.150 <<EOF
          kubectl create namespace monitoring || true
          kubectl apply -f manifests/monitoring/
          EOF
