name: Observability Stack

on:
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load inventory
        shell: bash
        run: |
          set -a
          source inventory/hosts.env
          set +a
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV

      - name: Download kubeconfig artifact
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig

      - name: Fix kubeconfig server endpoint
        shell: bash
        run: |
          set -euxo pipefail
          sed -i "s|server: https://127.0.0.1:6443|server: https://$MASTER_IP:6443|" kubeconfig.yaml

      - name: Validate kubeconfig
        shell: bash
        run: |
          set -euxo pipefail
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl cluster-info

      - name: Deploy Observability Stack
        shell: bash
        run: |
          set -euxo pipefail
          export KUBECONFIG=$PWD/kubeconfig.yaml

          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f manifests/monitoring
